//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class buy_and_sell_report
    {
        public string StockCode { get; set; }
        public string StockName { get; set; }
        public Nullable<int> globalCompany { get; set; }
        public Nullable<int> investmentTrust { get; set; }
        public Nullable<int> Dealer_1 { get; set; }
        public Nullable<int> Dealer_2 { get; set; }
        public Nullable<int> total { get; set; }
        public string stock_date { get; set; }
        public int id_BuyAndSell { get; set; }
    }
}
