//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mymessage
    {
        public int messageID { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string main { get; set; }
        public Nullable<int> replyID { get; set; }
        public Nullable<int> heart { get; set; }
        public Nullable<int> dislike { get; set; }
        public string wholike { get; set; }
        public string whohate { get; set; }
        public Nullable<System.DateTime> initDate { get; set; }
    }
}
