//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenues
    {
        public string IdAndName { get; set; }
        public string stockId { get; set; }
        public string stockName { get; set; }
        public Nullable<double> JanOne { get; set; }
        public Nullable<double> JanOneYOY { get; set; }
        public Nullable<double> FebOne { get; set; }
        public Nullable<double> FebOneYOY { get; set; }
        public Nullable<double> MarOne { get; set; }
        public Nullable<double> MarOneYOY { get; set; }
        public Nullable<double> AprOne { get; set; }
        public Nullable<double> AprOneYOY { get; set; }
        public Nullable<double> MayOne { get; set; }
        public Nullable<double> MayOneYOY { get; set; }
        public Nullable<double> JunOne { get; set; }
        public Nullable<double> JunOneYOY { get; set; }
        public Nullable<double> JulOne { get; set; }
        public Nullable<double> JulOneYOY { get; set; }
        public Nullable<double> AugOne { get; set; }
        public Nullable<double> AugOneYOY { get; set; }
        public Nullable<double> SepOne { get; set; }
        public Nullable<double> SepOneYOY { get; set; }
        public Nullable<double> OctOne { get; set; }
        public Nullable<double> OctOneYOY { get; set; }
        public Nullable<double> NovOne { get; set; }
        public Nullable<double> NovOneYOY { get; set; }
        public Nullable<double> DecOne { get; set; }
        public Nullable<double> DecOneYOY { get; set; }
        public Nullable<double> JanTwo { get; set; }
        public Nullable<double> JanTwoYOY { get; set; }
        public Nullable<double> FebTwo { get; set; }
        public Nullable<double> FebTwoYOY { get; set; }
    }
}
