//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockPrice
    {
        public string stockID { get; set; }
        public string stockName { get; set; }
        public Nullable<int> numOfSharesTrade { get; set; }
        public Nullable<int> numOfTrade { get; set; }
        public Nullable<long> moneyOfDeal { get; set; }
        public string openPrice { get; set; }
        public string highPrice { get; set; }
        public string lowPrice { get; set; }
        public string endPrice { get; set; }
        public string stockDate { get; set; }
        public int id { get; set; }
    }
}
